//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Olx.BLL.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Olx.BLL.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your account has been deleted by the site administrator.
        /// </summary>
        internal static string AccountDeleted {
            get {
                return ResourceManager.GetString("AccountDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your account is locked.
        /// </summary>
        internal static string AccountLocked {
            get {
                return ResourceManager.GetString("AccountLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Account removed.
        /// </summary>
        internal static string AccountRemoved {
            get {
                return ResourceManager.GetString("AccountRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your account has been unlocked.
        /// </summary>
        internal static string AccountUnlocked {
            get {
                return ResourceManager.GetString("AccountUnlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The admin has deleted your advert.&quot;{0}&quot;..
        /// </summary>
        internal static string AdminDeleteAdvert {
            get {
                return ResourceManager.GetString("AdminDeleteAdvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The admin has locked your advert &quot;{0}&quot;..
        /// </summary>
        internal static string AdminLockAdvert {
            get {
                return ResourceManager.GetString("AdminLockAdvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your advert has been deleted..
        /// </summary>
        internal static string AdvertDeleted {
            get {
                return ResourceManager.GetString("AdvertDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Due to violation of the rules and non-compliance with the site&apos;s policy..
        /// </summary>
        internal static string AdvertDeletedDefault {
            get {
                return ResourceManager.GetString("AdvertDeletedDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your advert has been added to favorites..
        /// </summary>
        internal static string AdvertInFavorites {
            get {
                return ResourceManager.GetString("AdvertInFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Advert is locked.
        /// </summary>
        internal static string AdvertLocked {
            get {
                return ResourceManager.GetString("AdvertLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Areas - {0}.
        /// </summary>
        internal static string AreasCount {
            get {
                return ResourceManager.GetString("AreasCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start areas update ....
        /// </summary>
        internal static string AreasUpdate {
            get {
                return ResourceManager.GetString("AreasUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Backup successfully created..
        /// </summary>
        internal static string BackupCreated {
            get {
                return ResourceManager.GetString("BackupCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Backup process has started..
        /// </summary>
        internal static string BackupStart {
            get {
                return ResourceManager.GetString("BackupStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Database update succeeded!.
        /// </summary>
        internal static string DataBaseUpdateSucceeded {
            get {
                return ResourceManager.GetString("DataBaseUpdateSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Email confirmation.
        /// </summary>
        internal static string EmailConfirmation {
            get {
                return ResourceManager.GetString("EmailConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your email is not confirmed. Please check your inbox for confirmation..
        /// </summary>
        internal static string EmailNotConfirmed {
            get {
                return ResourceManager.GetString("EmailNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Your account has been locked due to too many unsuccessful login attempts.
        /// </summary>
        internal static string FailedLoginAttempts {
            get {
                return ResourceManager.GetString("FailedLoginAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на For an indefinite period.
        /// </summary>
        internal static string Indefinitely {
            get {
                return ResourceManager.GetString("Indefinitely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Locked until.
        /// </summary>
        internal static string LockedUntil {
            get {
                return ResourceManager.GetString("LockedUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New Post data successfully updated !!!.
        /// </summary>
        internal static string NPUpdateCompleted {
            get {
                return ResourceManager.GetString("NPUpdateCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на reCaptcha validation error.
        /// </summary>
        internal static string reCaptchaValidationError {
            get {
                return ResourceManager.GetString("reCaptchaValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Regions - {0}.
        /// </summary>
        internal static string RegionsCount {
            get {
                return ResourceManager.GetString("RegionsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start regions update .....
        /// </summary>
        internal static string RegionsUpdate {
            get {
                return ResourceManager.GetString("RegionsUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Start settlements update ....
        /// </summary>
        internal static string SettlemensUpdate {
            get {
                return ResourceManager.GetString("SettlemensUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settlements - {0}.
        /// </summary>
        internal static string SettlementsCount {
            get {
                return ResourceManager.GetString("SettlementsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User &quot;{0}&quot; added your advert &quot;{1}&quot; to favorites..
        /// </summary>
        internal static string UserAddedToFavorites {
            get {
                return ResourceManager.GetString("UserAddedToFavorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User &quot;{0}&quot; bought your advert &quot;{1}&quot;.
        /// </summary>
        internal static string UserBoughtAdvert {
            get {
                return ResourceManager.GetString("UserBoughtAdvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User  bought your advert.
        /// </summary>
        internal static string UserBouth {
            get {
                return ResourceManager.GetString("UserBouth", resourceCulture);
            }
        }
    }
}
